# Generated by Django 5.2.7 on 2025-10-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BSIT', 'BS in Information Technology'), ('BSCS', 'BS in Computer Science'), ('BSEE', 'BS in Electrical Engineering'), ('BSTM', 'BS in Technology Management')], default='BSIT', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
