# Generated by Django 5.2.7 on 2025-11-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_student_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
    ]
