# Generated by Django 5.2.7 on 2025-11-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_remove_student_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
